# 服务端口
server:
  port: 8005
# 服务名
# 数据库
spring:
  # 服务名
  application:
    name: service-msm
  # 环境切换
  profiles:
    active: dev

    # 服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # redis设置
  redis:
    port: 6379
    host: 192.168.0.101
    password: wIe2Y%0wHXFcGY$pHy5jKDyAgYkiXa!A
    database: 0
    lettuce:
      shutdown-timeout:
    timeout: 1800000
    jedis:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 20
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认为8
        max-idle: 5
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
#
## 日志
#logging:
#  level: warn

alliyun:
  keyId: 00
  keySecret: 00
  signName: 00
  templateCode: 00