# 激活
spring:
  profiles:
    active: dev
  application:
    name: service_oss
  # 图片访问路径 磁盘
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:E:/images/


# 端口
server:
  port: 8001

# 服务名

alliyun:
  oss:
    file:
      endpoint: oss-cn-guangzhou.aliyuncs.com
      keyId: LTAI4GCBmSbHEJGEDfeAMdt3
      keySecret: yNEkIHs6vMf4kKUNDjeEUDzyvo1L91
      bucketName: plat-bck

nginx:
  port: 81